import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import { Geist } from "next/font/google";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import NaviHead from "./components/Header/Header";
import Navifoot from "./components/Footer/Footer";

// فونت‌های Geist برای بخش‌های انگلیسی یا کد (اختیاری)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// فونت اصلی سایت برای محتوای فارسی و انگلیسی
const vazir = Vazirmatn({ 
  subsets: ["latin", "arabic"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Next.JS Baby",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // تنظیم زبان به فارسی و جهت به راست-به-چپ برای کل صفحه
    <html lang="fa" dir="rtl">
      {/*
        کلاس فونت وزیرمتن را به body اضافه می‌کنیم تا فونت پیش‌فرض سایت باشد.
        متغیرهای فونت Geist هم برای استفاده‌های خاص در دسترس هستند.
      */}
      <body
        className={`${vazir.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NaviHead />
        {/* بهتر است محتوای اصلی هر صفحه داخل تگ <main> قرار بگیرد */}
        <main className="min-h-screen">
          {children}
        </main>
        <Navifoot />
      </body>
    </html>
  );
}
